### ISSUE TITLE
ImportError when importing tensorflow

### ISSUE THREAD

**Issue by lpatruno** [RealScout/deep-learning-images#6]
Hi guys,

Thanks for this repo. However, after creating both the base and tensorflow AMIs and launching a new instance I ran into an exception. When I ssh onto the box and try to import tensorflow into the Python interpreter, this error is raised:

`ImportError: /usr/local/bin/../lib/libstdc++.so.6: version 'CXXABI_1.3.8' not found (required by /usr/local/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so)`

Any ideas?

**Comment by lpatruno** [comment]
This solution fixed the problem for me

http://stackoverflow.com/questions/39844772/cxxabi-1-3-8-not-found-in-tensorflow-gpu-install-from-source#answer-39856855

**Comment by graphaelli** [comment]
Reopening, I'd like this to work out of the box.

**Comment by lpatruno** [comment]
Nice. Thanks @graphaelli

**Comment by snbaker** [comment]
I had the same issue after launching an instance based on the AMI created here but my solution was slightly different from that posted on Stack Overflow (where the user appears to have installed anaconda manually). Instead of the `cp` command posted in the linked answer, I had to run `cp /usr/lib/x86_64-linux-gnu/libstdc++.so.6 /usr/local/lib/libstdc++.so.6`

**Comment by graphaelli** [comment]
anaconda is bringing its own `libstdc++.so` -  Trying to dump that now in favor of the system python 3.5 - something I hadn't gotten around to since the update to Ubuntu 16.04 in 8a66eea0c6163c73cb91495e57a0cd2e09a82857

**Comment by lpatruno** [comment]
This works out of the box. Thanks @graphaelli !

**Comment by graphaelli** [comment]
awesome, thanks for checking back in @lpatruno
